"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-secure-e7a+q=#eg_ys#9^^fl^a-d3l9%6i#v*1h&hfckbb5dve36=&dd",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pagina_principal',
    'prestamo',
    'usuario',
    "herramienta",
    "almacen",
    "configuracion",
    'chatbot',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

try:
    from configuracion.manager import ConfigurationManager
    DATABASES = {
        "default": ConfigurationManager(base_dir=BASE_DIR).get_active_django_db_dict()
    }
except Exception:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation.MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation.CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation.NumericPasswordValidator"
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "es-co"

TIME_ZONE = "America/Bogota"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='desarrollo@local.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='desarrollo@local.com')

LOGIN_URL = '/'

# =============================================================================
# POLÍTICAS DE VERIFICACIÓN SOFIAPLUS EN REGISTRO DE USUARIOS
# =============================================================================
# TODO: [DECISIÓN DE NEGOCIO PENDIENTE] ALLOW_MANUAL_REGISTRATION
# Define si se permite el registro de usuarios cuyo documento no se encuentre en SofiaPlus.
# - False (por defecto): Bloquea la creación; solo aprendices oficiales del SENA pueden crear cuenta.
# - True: Permite registro manual excepcional (se guardará con verificado_sofia_plus = False).
ALLOW_MANUAL_REGISTRATION = config('ALLOW_MANUAL_REGISTRATION', default=False, cast=bool)

# TODO: [DECISIÓN DE NEGOCIO PENDIENTE] SOFIAPLUS_FALLBACK_POLICY
# Define la política de registro cuando el servicio externo de SofiaPlus no responda (timeout o caída):
# - 'ALLOW_PENDING' (por defecto): Permite crear la cuenta en estado provisional
#   (verificado_sofia_plus = False) para no bloquear al aprendiz en terreno, pendiente de confirmación.
# - 'REJECT': Bloquea temporalmente el registro con mensaje de reintento.
SOFIAPLUS_FALLBACK_POLICY = config('SOFIAPLUS_FALLBACK_POLICY', default='ALLOW_PENDING')

# =============================================================================
# ASISTENTE VIRTUAL IA (GEMINI API)
# =============================================================================
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-flash-lite-latest')
CHATBOT_RATE_LIMIT_RPM = config('CHATBOT_RATE_LIMIT_RPM', default=20, cast=int)
CHATBOT_ENABLE_LOGGING = config('CHATBOT_ENABLE_LOGGING', default=True, cast=bool)

